unrestricted_licenses:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - 0BSD
  - MIT

restricted_licenses:
  - bzip2-1.0.5
  - AGPL-1.0
  - AGPL-3.0
  - BSD-2-Clause-FreeBSD
  - BSD-2-Clause-NetBSD
  - eCos-2.0
  - GFDL-1.1
  - GFDL-1.2
  - GFDL-1.3
  - GPL-1.0-only
  - GPL-1.0-or-later
  - GPL-2.0+
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-2.0-with-autoconf-exception
  - GPL-2.0-with-bison-exception
  - GPL-2.0-with-classpath-exception
  - GPL-2.0-with-GCC-exception
  - GPL-2.0-with-font-exception
  - GPL-3.0-only
  - GPL-3.0-or-later
  - GPL-3.0+
  - GPL-3.0-with-autoconf-exception
  - GPL-3.0-with-GCC-exception
  - LGPL-2.0-only
  - LGPL-2.0+
  - LGPL-2.0-or-later
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - LGPL-3.0+
  - NPL-1.0
  - NPL-1.1
  - Nunit
  - OSL-1.0
  - OSL-1.1
  - OSL-2.0
  - OSL-2.1
  - OSL-3.0
  - QPL-1.0
  - Sleepycat
  - StandardML-NJ
  - wxWindows

allowlisted_modules:
  # MIT: https://github.com/ghodss/yaml/blob/master/LICENSE
  - github.com/ghodss/yaml
  # BSD: https://github.com/gogo/protobuf/blob/master/LICENSE
  - github.com/gogo/protobuf
  # Apache 2.0
  - github.com/spf13/cobra
  # https://github.com/xeipuuv/gojsonpointer/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonpointer
  # https://github.com/xeipuuv/gojsonreference/blob/master/LICENSE-APACHE-2.0.txt
  - github.com/xeipuuv/gojsonreference
  # MIT: https://github.com/kubernetes-sigs/yaml/blob/master/LICENSE
  - sigs.k8s.io/yaml
  # BSD-2-Clause: https://github.com/rcrowley/go-metrics/blob/master/LICENSE
  - github.com/rcrowley/go-metrics